name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          key: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

      - name: install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: build
        run: npm run next build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get -y install lftp
          lftp << !
            open -u $FTP_USER,$FTP_PASSWORD ftp://$FTP_HOST
            mirror --delete --reverse --parallel=20 --verbose --exclude-glob .pureftpd-upload* out/ colette-szczepaniak.com/
          !
